### ISSUE TITLE
Tomb Raider Underworld Screen Glitching

### ISSUE THREAD

**Issue by UroshUchiha** [EKA2L1/EKA2L1#111]
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4556818/EKA2L1.log)

Tomb Raider Underworld completely fails to launch
Log file uploaded.
![image](https://user-images.githubusercontent.com/36758864/80685198-1abde900-8ac7-11ea-84ac-0ff6d2bc3721.png)

**Comment by pent0** [comment]
Please retest! It should work now!

**Comment by UroshUchiha** [comment]
The game goes into main menu now.
Still not playable though cause of visual glitches that appear once you start the game.
