### ISSUE TITLE
CMake fails on Qt5OpenGLWidgets

### ISSUE THREAD

**Issue by Shoegzer** [EKA2L1/EKA2L1#315]
**Describe the bug**

CMake fails to complete due to inability to find package configuration file provided by `Qt5OpenGLWidgets`, even though `libqt5opengl5-dev` is installed.  @pent0 is another dependency necessary?

**Your PC or smartphone specs**
- OS version: Linux Mint 20.2 / kernel 5.11
- The CPU you are using: Intel i7-10870H
- The GPU you are using: Nvidia GTX 3070
- Compiler version: gcc-11.1.0
- CMake version: 3.20.2
- Qt version: 5.12.8

**Log**
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5OpenGLWidgets"
  with any of the following names:

    Qt5OpenGLWidgetsConfig.cmake
    qt5openglwidgets-config.cmake

  Add the installation prefix of "Qt5OpenGLWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5OpenGLWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5OpenGLWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/emu/qt/CMakeLists.txt:15 (find_package)
```

**Comment by pent0** [comment]
No, it's not necessary. You definitely install the right package. I am not sure what is the problem sorry. We don't do any special kinds of stuff in the CMake, so you should check your dependency again, or clear the cache.

**Comment by pent0** [comment]
I'm not sure if you are doing it, but you need to set CMAKE_PREFIX_PATH to your qt installation too.

**Comment by Shoegzer** [comment]
Thanks for your help @pent0.  

I start with a fresh eka2l1 build directory with each compile so the cache is clear.  Also following your suggestion, I set `CMAKE_PREFIX_PATH` to the qt installation by adding it as a cmake argument as below but got the same results unfortunately.  I assume this is what you meant?

`cmake .. -DEKA2L1_BUILD_VULKAN_BACKEND=OFF -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake`

Also, here's the contents of that directory, is anything missing?
``` 
$ ls /usr/lib/x86_64-linux-gnu/cmake
Boost-1.71.0                      DBus1                 Qt5OpenGLExtensions  Qt5WebEngineCore
boost_atomic-1.71.0               glslang               Qt5Positioning       Qt5WebEngineWidgets
boost_chrono-1.71.0               harfbuzz              Qt5PositioningQuick  Qt5WebKit
boost_context-1.71.0              PulseAudio            Qt5PrintSupport      Qt5WebKitWidgets
boost_date_time-1.71.0            Qt5                   Qt5Qml               Qt5Widgets
BoostDetectToolset-1.71.0.cmake   Qt5Concurrent         Qt5Quick             Qt5X11Extras
boost_filesystem-1.71.0           Qt5Core               Qt5QuickCompiler     Qt5Xml
boost_headers-1.71.0              Qt5DBus               Qt5QuickTest         Qt5XmlPatterns
boost_prg_exec_monitor-1.71.0     Qt5Designer           Qt5QuickWidgets      SDL2
boost_program_options-1.71.0      Qt5Gui                Qt5Sql               SFML
boost_serialization-1.71.0        Qt5Help               Qt5Svg               SPIRV-Headers
boost_system-1.71.0               Qt5LinguistTools      Qt5Test              SPIRV-Tools
boost_test_exec_monitor-1.71.0    Qt5Multimedia         Qt5UiPlugin          SPIRV-Tools-link
boost_thread-1.71.0               Qt5MultimediaWidgets  Qt5UiTools           SPIRV-Tools-opt
boost_unit_test_framework-1.71.0  Qt5Network            Qt5WebChannel        SPIRV-Tools-reduce
boost_wserialization-1.71.0       Qt5OpenGL             Qt5WebEngine
```
Finally, here's the CMake logs in case they provide any clues:

[CMakeError.log](https://github.com/EKA2L1/EKA2L1/files/6874627/CMakeError.log)
[CMakeOutput.log](https://github.com/EKA2L1/EKA2L1/files/6874628/CMakeOutput.log)

This is particularly odd since I use ths test system to compile several other projects that use Qt and CMake and they don't have this issue.  Hopefully this is a matter of simple oversight but thanks for any help you have.

**Comment by pent0** [comment]
It's ok, this module is decrapated in Qt 5 and in Qt6 it's renamed to QtOpenGLWidgets. In qt5 it should be Qt5::OpenGL. I will fix it as soon as I can. Thanks for the report.

**Comment by pent0** [comment]
Hi, I have pushed a fix. Please try again.

**Comment by Shoegzer** [comment]
Thanks @pent0 , tested with clean build dir / cmake cache though I'm still getting the same issue unfortunately.  Just let me know if you need logs etc.

**Comment by pent0** [comment]
Hi, let's try again. I forgot to change what required components on FindPackage too.

**Comment by Shoegzer** [comment]
Okay the CMake issue seems to be fixed and we're getting further, however now I'm getting this:
```
[ 95%] Building CXX object src/tests/CMakeFiles/ekatests.dir/epoc/vfs.cpp.o
Segmentation fault (core dumped)
make[2]: *** [src/emu/qt/CMakeFiles/eka2l1_qt.dir/build.make:319: ../src/emu/qt/translations/eka2l1_en_US.ts] Error 139
make[1]: *** [CMakeFiles/Makefile2:3079: src/emu/qt/CMakeFiles/eka2l1_qt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Again just let me know if you need anything else.

**Comment by pent0** [comment]
This seems like a compiler bug with the translation, seems really weird and
hard to tackle. Let's not try to build all and try to build only the
eka2l1_qt target to see if it's better.

I may try myself with qt5 when I have time.

Vào Th 4, 28 thg 7, 2021 vào lúc 11:08 Shoegzer ***@***.***>
đã viết:

**Comment by pent0** [comment]
Give another try.

**Comment by Shoegzer** [comment]
Thanks, but same results unfortunately:
```
Segmentation fault (core dumped)
make[2]: *** [src/emu/qt/CMakeFiles/eka2l1_qt.dir/build.make:319: ../src/emu/qt/translations/eka2l1_en_US.ts] Error 139
make[2]: *** Waiting for unfinished jobs....
[ 95%] Building CXX object src/tests/CMakeFiles/ekatests.dir/epoc/loader/e32img.cpp.o
Segmentation fault (core dumped)
make[2]: *** [src/emu/qt/CMakeFiles/eka2l1_qt.dir/build.make:315: ../src/emu/qt/translations/eka2l1.ts] Error 139
make[1]: *** [CMakeFiles/Makefile2:3079: src/emu/qt/CMakeFiles/eka2l1_qt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
In case it's helpful I also tried compiling with gcc-10 via CMake flag but got the same results.

**Comment by pent0** [comment]
I mean qt compiler bug about translation file. I don't know why yet. I exclude the original translation file, with no locale info.

**Comment by pent0** [comment]
You did not try building with eka2l1_qt separately. Give it some.

**Comment by Shoegzer** [comment]
Thanks, I assume you mean to run a `make -j9 TARGET=eka2l1_qt`, so I did that.  However I'm getting the same results.

**Comment by pent0** [comment]
Oh that's sad, I will try to setup virtual env to resolve myself, not floating this discussion. Sorry for the nuisance !

**Comment by Shoegzer** [comment]
Not a nuisance at all.  I'm happy to help test whenever you're ready.

**Comment by pent0** [comment]
Hi, I think I fixed it this time. Let's try again!

**Comment by Shoegzer** [comment]
Hey thanks, but not quite yet!
```
make[2]: *** [src/emu/qt/CMakeFiles/eka2l1_qt.dir/build.make:588: src/emu/qt/CMakeFiles/eka2l1_qt.dir/src/device_install_dialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3080: src/emu/qt/CMakeFiles/eka2l1_qt.dir/all] Error 2
```
[Here](https://pastebin.com/HkHEM5Fa) is the full build log showing other errors towards the end of the compile process.  Hope it helps.

**Comment by pent0** [comment]
Looks like there are more incompatibilities than I thought... I have set up CI and downloading qt5 to fix it, please wait.

**Comment by pent0** [comment]
Should be fine now

**Comment by Shoegzer** [comment]
Not quite yet:
```
[ 96%] Building CXX object src/emu/qt/CMakeFiles/eka2l1_qt.dir/src/package_manager_dialog.cpp.o
/home/testing/Desktop/eka2l1/EKA2L1/src/emu/qt/src/main.cpp: In function ‘int main(int, char**)’:
/home/testing/Desktop/eka2l1/EKA2L1/src/emu/qt/src/main.cpp:59:69: error: ‘class QTranslator’ has no member named ‘language’
   59 |                 settings.setValue(LANGUAGE_SETTING_NAME, translator.language());
      |                                                                     ^~~~~~~~
[ 96%] Building CXX object src/emu/qt/CMakeFiles/eka2l1_qt.dir/src/seh_handler.cpp.o
make[2]: *** [src/emu/qt/CMakeFiles/eka2l1_qt.dir/build.make:616: src/emu/qt/CMakeFiles/eka2l1_qt.dir/src/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/testing/Desktop/eka2l1/EKA2L1/src/emu/qt/src/device_install_dialog.cpp: In member function ‘void device_install_dialog::on_install_triggered()’:
/home/testing/Desktop/eka2l1/EKA2L1/src/emu/qt/src/device_install_dialog.cpp:189:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  189 |         std::this_thread::sleep_for(std::chrono::milliseconds(1));
      |                           ^~~~~~~~~
make[2]: *** [src/emu/qt/CMakeFiles/eka2l1_qt.dir/build.make:588: src/emu/qt/CMakeFiles/eka2l1_qt.dir/src/device_install_dialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3080: src/emu/qt/CMakeFiles/eka2l1_qt.dir/all] Error 2
```

**Comment by pent0** [comment]
Please use qt 5.15. I can't lower down the requirements.

**Comment by Shoegzer** [comment]
Ah, right.  I use Qt 5.12 by default, though I do have Qt 5.15 in a different dir (/opt/qt515).  That said, I tried compiling using it and I get this message again:
```
CMake Error at /opt/qt515/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/emu/qt/CMakeLists.txt:22 (find_package)
```
I tried adding `-DCMAKE_PREFIX_PATH=/opt/qt515/lib/cmake` but I get the same thing.  Here's the contents of that directory (notice no Qt5LinguistTools):
```
/opt/qt515/lib/cmake$ ls -la
total 136
drwxr-xr-x 32 root root  4096 Apr  6 19:16 .
drwxr-xr-x  5 root root 12288 Apr  6 19:16 ..
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5AccessibilitySupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Concurrent
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Core
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5DBus
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5DeviceDiscoverySupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5EdidSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5EglFSDeviceIntegration
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5EglSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5EventDispatcherSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5FbSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5FontDatabaseSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5GlxSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Gui
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5InputSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5LinuxAccessibilitySupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Network
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5OpenGL
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5OpenGLExtensions
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5PlatformCompositorSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5PrintSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5ServiceSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Sql
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Test
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5ThemeSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5VulkanSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Widgets
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5XcbQpa
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5XkbCommonSupport
drwxr-xr-x  2 root root  4096 Apr  6 19:16 Qt5Xml
```

**Comment by pent0** [comment]
Have you tried this [this](https://stackoverflow.com/questions/51698075/cmake-cannot-find-qt5linguisttools-in-docker-ubuntu-18-04) ? It seems more like a missing package problem.

**Comment by pent0** [comment]
Actually, I can lower down the requirements! You can switch back, I will do later.

**Comment by Shoegzer** [comment]
Ah, nice.  I was going to say I already installed `qttools5-dev` but as that post indicates, it's installed in the default `/usr/lib/x86_64-linux-gnu/cmake` directory (which is 5.12), not ` /opt/qt515/lib/cmake` (which is 5.15).  So yes, lowering the requirements would be a big help.  :)

**Comment by pent0** [comment]
Let's try again (don't need to reclone).

**Comment by Shoegzer** [comment]
I assume you mean using Qt 5.12?  When I compile with that I get this:
```
/home/testing/Desktop/eka2l1/EKA2L1/src/emu/qt/src/settings_dialog.cpp: In constructor ‘settings_dialog::settings_dialog(QWidget*, eka2l1::system*, eka2l1::drivers::emu_controller*, eka2l1::config::app_settings*, eka2l1::config::state&)’:
/home/testing/Desktop/eka2l1/EKA2L1/src/emu/qt/src/settings_dialog.cpp:271:46: error: ‘class QTranslator’ has no member named ‘language’
  271 |             QString locale_name = translator.language();
      |                                              ^~~~~~~~
/home/testing/Desktop/eka2l1/EKA2L1/src/emu/qt/src/settings_dialog.cpp:373:56: error: ‘textActivated’ is not a member of ‘QComboBox’
  373 |     connect(ui_->control_profile_combobox, &QComboBox::textActivated, this, &settings_dialog::on_control_profile_choosen_another);
      |                                                        ^~~~~~~~~~~~~
[ 96%] Building CXX object src/emu/qt/CMakeFiles/eka2l1_qt.dir/eka2l1_qt_autogen/EWIEGA46WW/qrc_eka2l1.cpp.o
[ 97%] Building CXX object src/emu/qt/CMakeFiles/eka2l1_qt.dir/eka2l1_qt_autogen/EJRQKI7XPS/qrc_languages.cpp.o
[ 97%] Building CXX object src/emu/qt/CMakeFiles/eka2l1_qt.dir/eka2l1_qt_autogen/NSED55MBZJ/qrc_style.cpp.o
make[2]: *** [src/emu/qt/CMakeFiles/eka2l1_qt.dir/build.make:672: src/emu/qt/CMakeFiles/eka2l1_qt.dir/src/settings_dialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3080: src/emu/qt/CMakeFiles/eka2l1_qt.dir/all] Error 2
```

**Comment by pent0** [comment]
Okay, I fix this batch of errors. Hope that's the end ;)

**Comment by Shoegzer** [comment]
Hey thanks, we're getting closer!  Compilation is fixed for Qt 5.12 at least, though I get the following at runtime:
```
$ ./eka2l1_qt 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
As shown in my directory listing above, the Qt 5.12 installation does not have a "plugins" directory.  My Qt 5.15 installation has `/opt/qt515/plugins/xcbglintegrations` which I assume would fix this issue; however when attempting to compile with Qt 5.15 I still get this error:
```
CMake Error at /opt/qt515/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake
```

**Comment by pent0** [comment]
Can you try getting the information displays in the 52 upvotes in this [post](https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without)?

I have checked other emulators qt code, they do not seem to bundle any plugins with the shipped binary. So I don't think we are doing anything wrong.

**Comment by Shoegzer** [comment]
Ah right, when I perform `export QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu//qt5/plugins/`, eka2l1-qt runs (and looks good!).  I could make that part of my shell, however it would conflict with other projects that use self-compiled Qt (5.15 in this case).  Is there any way the code can detect the plugin path at compile-time or runtime?

I'd also like to help you get it compiling with systems that self-compile Qt, particularly since I have a good test case for it.

**Comment by pent0** [comment]
>  Is there any way the code can detect the plugin path at compile-time or runtime

This is out of my league, I don't handle this directly :( Rather to put the questions while other projects do not need this plugin is a good idea. I don't actually know why sadly, I only know OpenGL on Qt needs xcb plugin.

> help you get it compiling with systems that self-compile Qt

Someone on Discord says they are handling this regarding embedded system like Raspberry with ARM64 CPU running Linux. I won't port it myself at the moment, sorry. But regarding x64 arch system that is self compile qt, sure.

**Comment by Shoegzer** [comment]
> This is out of my league, I don't handle this directly :( Rather to put the questions while other projects do not need this plugin is a good idea. I don't actually know why sadly, I only know OpenGL on Qt needs xcb plugin.

Fair enough.  Many of the other emulation projects I test use Qt and I've never encountered this before.  Hopefully you can find a way to resolve this so it can at least be launched from command-line without a static export in shell.  I'm doing some research myself but haven't found anything yet, though as always I'm happy to help you test anything.

> Someone on Discord says they are handling this regarding embedded system like Raspberry with ARM64 CPU running Linux. I won't port it myself at the moment, sorry. But regarding x64 arch system that is self compile qt, sure.

Can you join him to this discussion?  Perhaps he has ideas on how to resolve compiling your project with non-repo Qt.  Since this seems to be fairly common scenario for those of us who test emulators to help with issues, I'd recommend keeping this open until we can find a way to do it.

**Comment by pent0** [comment]
Maybe let's open another issue when there is interest since this one was to solved compile issues (I will try to solve the xcb one too, you can open an issue if required, but I will keep that in my personal check notes).

I don't think they are active at the moment, when they have motivation again I will ask them to open a new Github discussion. Since this emulator is not used by many outsides of Windows usage (it does not mean a port is not welcomed).

Thanks for raising compile issue!
